import { NextRequest, NextResponse } from "next/server";
import { getTokenFromRequest, getWorkspaceApiToken } from "@/lib/auth";
const LIST = "901420989525";
type Demand = { id?: string; date?: string; company: string; segment?: "Retail"|"Industrial"; industry: string; associate: string; market: string; location: string; minSqm: number; maxSqm: number; priority: "Priority"|"Normal"; status: "Active"|"Shelved"; timeline: string; purpose: string; alternatives?: string };
const token = (r: NextRequest) => getTokenFromRequest(r) || getWorkspaceApiToken();
const clean = (v: unknown) => typeof v === "string" ? v.trim() : "";
function normalise(v: any): Demand | null { if (!v || !clean(v.company) || !clean(v.location)) return null; return { id: v.id, date: clean(v.date), company: clean(v.company), segment: v.segment === "Industrial" ? "Industrial" : "Retail", industry: clean(v.industry), associate: clean(v.associate), market: clean(v.market), location: clean(v.location), minSqm: Number(v.minSqm)||0, maxSqm: Number(v.maxSqm)||0, priority: v.priority === "Priority" ? "Priority" : "Normal", status: v.status === "Shelved" ? "Shelved" : "Active", timeline: clean(v.timeline), purpose: clean(v.purpose), alternatives: clean(v.alternatives) }; }
const parse = (task: any) => { try { const p = JSON.parse(task.text_content || task.description || task.markdown_description || ""); const d = normalise(p?.echoDemand); return d ? { ...d, id: String(task.id), url: task.url || "" } : null; } catch { return null; } };
async function list(tokenValue: string) { const r = await fetch(`https://api.clickup.com/api/v2/list/${LIST}/task?include_closed=true&include_markdown_description=true&page=0`, { headers: { Authorization: tokenValue }, cache: "no-store" }); if (!r.ok) throw new Error("Unable to read the Demands archive from ClickUp."); const b = await r.json(); return (b.tasks || []).map(parse).filter(Boolean); }
const description = (d: Demand) => JSON.stringify({ echoDemand: { ...d, id: undefined } }, null, 2);
export async function GET(req: NextRequest) { const t=token(req); if(!t)return NextResponse.json({error:"ClickUp authentication required."},{status:401}); try{return NextResponse.json({listId:LIST,demands:await list(t)});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load Demands."},{status:502});} }
export async function POST(req: NextRequest) { const t=token(req); if(!t)return NextResponse.json({error:"ClickUp authentication required."},{status:401}); try { const body=await req.json(); const incoming=(Array.isArray(body.demands)?body.demands:[body]).map(normalise).filter(Boolean) as Demand[]; if(!incoming.length)return NextResponse.json({error:"No valid demand records were supplied."},{status:400}); const existing=await list(t); const known=new Set(existing.map((d: any)=>`${d.company}|${d.location}|${d.date}`.toLowerCase())); const created=[]; for(const d of incoming){const key=`${d.company}|${d.location}|${d.date}`.toLowerCase(); if(known.has(key))continue; const r=await fetch(`https://api.clickup.com/api/v2/list/${LIST}/task`,{method:"POST",headers:{Authorization:t,"Content-Type":"application/json"},body:JSON.stringify({name:`${d.date||"Undated"} · ${d.company} · ${d.location}`,description:description(d),tags:["demand",(d.segment||"Retail").toLowerCase(),d.status.toLowerCase()]})}); if(!r.ok)throw new Error(`ClickUp could not create ${d.company}.`); created.push(parse(await r.json())); known.add(key); } return NextResponse.json({success:true,created,skipped:incoming.length-created.length}); } catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to save demand."},{status:502});} }
export async function PATCH(req: NextRequest) { const t=token(req); if(!t)return NextResponse.json({error:"ClickUp authentication required."},{status:401}); try { const b=await req.json(), d=normalise(b); if(!b.id||!d)return NextResponse.json({error:"A complete demand record is required."},{status:400}); const r=await fetch(`https://api.clickup.com/api/v2/task/${b.id}`,{method:"PUT",headers:{Authorization:t,"Content-Type":"application/json"},body:JSON.stringify({name:`${d.date||"Undated"} · ${d.company} · ${d.location}`,description:description(d)})}); if(!r.ok)throw new Error("ClickUp could not update this demand."); return NextResponse.json({success:true,demand:parse(await r.json())}); } catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update demand."},{status:502});} }

