-- Unified storage for Admin workspace configuration.
create table if not exists public.echo_modules (
  key text primary key,
  label text not null,
  enabled boolean not null default true,
  maintenance_mode boolean not null default false,
  display_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.echo_access_policies (
  id bigint generated by default as identity primary key,
  subject_type text not null check (subject_type in ('default','role','department','user')),
  subject_key text not null,
  module_key text not null references public.echo_modules(key) on delete cascade,
  can_view boolean not null default true,
  can_manage boolean not null default false,
  unique (subject_type, subject_key, module_key)
);

alter table public.echo_modules enable row level security;
alter table public.echo_access_policies enable row level security;

insert into public.echo_modules (key, label, display_order) values
  ('dashboard','Dashboard',10), ('tasks','Tasks',20), ('notebook','Notebook',30),
  ('market-insights','Market Insights',40), ('demands','Demands',50),
  ('meetings','Meetings',60), ('minutes','Notetaker',70), ('forms','Forms',80),
  ('ask-echo','Ask Echo',90), ('email','Email & Notifications',100)
on conflict (key) do nothing;

insert into public.echo_access_policies (subject_type, subject_key, module_key, can_view, can_manage)
select 'default', 'all', key, true, false from public.echo_modules
on conflict (subject_type, subject_key, module_key) do nothing;
