-- Echo operational telemetry
-- Apply this migration in Supabase before enabling telemetry writes.
-- Audio, transcript content, prompts, and ClickUp records must never be stored here.

create table if not exists public.echo_telemetry (
  id bigint generated by default as identity primary key,
  user_id text,
  user_email text,
  occurred_at timestamptz not null default now(),
  source text not null check (source in ('echo_recording', 'uploaded_audio', 'meetstream_bot', 'ask_echo', 'notetaker_finalize')),
  operation text not null check (operation in ('audio_chunk', 'audio_upload', 'ask_echo', 'notetaker_finalize')),
  capture_mode text check (capture_mode in ('botless', 'bot', 'unknown')),
  provider text,
  model text,
  audio_seconds numeric(12, 3),
  file_size_bytes bigint,
  processing_ms integer not null default 0,
  queue_ms integer not null default 0,
  fallback_used boolean not null default false,
  retry_count integer not null default 0,
  success boolean not null default false,
  error_category text,
  error_message text,
  chunk_index integer,
  total_chunks integer,
  transcript_characters integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint echo_telemetry_nonnegative_metrics check (
    processing_ms >= 0 and queue_ms >= 0 and retry_count >= 0
    and (audio_seconds is null or audio_seconds >= 0)
    and (file_size_bytes is null or file_size_bytes >= 0)
    and (chunk_index is null or chunk_index >= 0)
    and (total_chunks is null or total_chunks > 0)
    and (transcript_characters is null or transcript_characters >= 0)
  )
);

create index if not exists echo_telemetry_occurred_idx
  on public.echo_telemetry (occurred_at desc);

create index if not exists echo_telemetry_source_occurred_idx
  on public.echo_telemetry (source, occurred_at desc);

create index if not exists echo_telemetry_provider_model_idx
  on public.echo_telemetry (provider, model, occurred_at desc);

create index if not exists echo_telemetry_user_occurred_idx
  on public.echo_telemetry (user_email, occurred_at desc);

create index if not exists echo_telemetry_operation_success_idx
  on public.echo_telemetry (operation, success, occurred_at desc);

alter table public.echo_telemetry enable row level security;

-- Telemetry is written and read by server routes using the Supabase service key.
-- No client-side policy is granted, preventing users from reading other users' events.

comment on table public.echo_telemetry is 'Operational Echo telemetry; never store audio, transcripts, prompts, or ClickUp content.';
comment on column public.echo_telemetry.source is 'Where the work originated: Echo recording, uploaded audio, MeetStream bot, Ask Echo, or Notetaker finalization.';
comment on column public.echo_telemetry.occurred_at is 'Event time in UTC with timezone; use this for reporting.';
