create table if not exists public.echo_forms_config (
  id text primary key check (id = 'global'),
  config jsonb not null default '{"admins":[],"departments":[],"mappings":[]}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.echo_forms_config enable row level security;

-- The server uses the service key for this singleton. No client-side policy is granted.

create table if not exists public.echo_ai_usage (
  id bigint generated by default as identity primary key,
  user_email text not null,
  model text not null,
  status text not null,
  latency_ms integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists echo_ai_usage_user_created_idx on public.echo_ai_usage (user_email, created_at desc);
create index if not exists echo_ai_usage_created_idx on public.echo_ai_usage (created_at desc);

alter table public.echo_ai_usage enable row level security;

-- Usage is written and read by server routes using the service key.
