"use client";

import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Plus, RefreshCw, Save, X } from "lucide-react";

type Sector = "industrial" | "retail";
type Article = { id: string; url: string; sector: Sector; date: string; company: string; event: string; implications: string; source: string };
type Draft = Omit<Article, "id" | "url">;
const emptyDraft = (sector: Sector): Draft => ({ sector, date: new Date().toISOString().slice(0, 10), company: "", event: "", implications: "", source: "" });
const isUrl = (value: string) => /^https?:\/\//i.test(value);

function inCurrentWeek(date: string) { const day = new Date(`${date}T00:00:00`); const now = new Date(); const start = new Date(now); start.setDate(now.getDate() - ((now.getDay() + 6) % 7)); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(start.getDate() + 7); return day >= start && day < end; }

export function MarketInsightsView() {
  const [sector, setSector] = useState<Sector>("industrial"); const [articles, setArticles] = useState<Article[]>([]); const [draft, setDraft] = useState<Draft | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [bulkOpen, setBulkOpen] = useState(false); const [bulkText, setBulkText] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const res = await fetch("/api/market-insights", { cache: "no-store" }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setArticles(data.articles || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load the archive."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => articles.filter((item) => item.sector === sector).sort((a,b) => b.date.localeCompare(a.date)), [articles, sector]);
  const weekly = useMemo(() => articles.filter((item) => inCurrentWeek(item.date)), [articles]);
  const generatedBrief = useMemo(() => { if (!weekly.length) return "Add this week’s articles to begin the executive brief."; const companies = [...new Set(weekly.map((a) => a.company))].slice(0, 3).join(", "); const implications = weekly.map((a) => a.implications).filter(Boolean).slice(0, 2).join(" "); return `${weekly.length} market signals were logged this week, led by ${companies}. ${implications}`; }, [weekly]);
  const save = async () => { if (!draft) return; setSaving(true); setError(""); try { const res = await fetch("/api/market-insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setDraft(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save article."); } finally { setSaving(false); } };
  const importBulk = async () => { setSaving(true); setError(""); try { const articlesToImport = JSON.parse(bulkText); if (!Array.isArray(articlesToImport)) throw new Error("Paste a JSON array of article records."); const res = await fetch("/api/market-insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ articles: articlesToImport }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setBulkOpen(false); setBulkText(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to import the archive."); } finally { setSaving(false); } };
  return <div className="max-w-[1500px] mx-auto space-y-6">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 border-b border-gray-200 pb-5"><div><p className="text-[11px] font-bold tracking-[0.18em] uppercase text-[#C9AB4C]">CRD Market Intelligence</p><h1 className="font-serif italic text-3xl text-[#003366] mt-1">Market Insights</h1><p className="text-sm text-gray-500 mt-2">Weekly market readout and a shared source archive for the team.</p></div><button onClick={load} className="h-10 px-3 bg-[#FFFCFB] border border-gray-300 text-[#003366] text-sm font-semibold flex items-center gap-2 hover:border-[#C9AB4C]"><RefreshCw size={15} className={loading ? "animate-spin" : ""}/> Refresh archive</button></div>
    <section className="bg-[#003366] text-white border-t-4 border-[#C9AB4C] p-5 md:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-wider uppercase text-[#E8D590]">Weekly executive brief</p><h2 className="font-serif italic text-2xl mt-1">This week’s market signal</h2></div><span className="text-xs font-semibold text-[#E8D590]">{weekly.length} articles</span></div><div className="grid lg:grid-cols-3 gap-5 mt-5"><div className="border-t border-white/25 pt-3"><p className="text-[11px] font-bold uppercase tracking-wider text-[#E8D590]">Market readout</p><p className="mt-2 text-sm leading-6">{generatedBrief}</p></div><div className="border-t border-white/25 pt-3"><p className="text-[11px] font-bold uppercase tracking-wider text-[#E8D590]">Emerging themes</p><p className="mt-2 text-sm leading-6">{weekly.length ? [...new Set(weekly.map((article) => article.company))].slice(0, 4).join(" · ") : "No themes yet."}</p></div><div className="border-t border-white/25 pt-3"><p className="text-[11px] font-bold uppercase tracking-wider text-[#E8D590]">Opportunities & risks</p><p className="mt-2 text-sm leading-6">{weekly.map((article) => article.implications).filter(Boolean).slice(0, 1).join(" ") || "Add implications to surface the opportunity and risk watchlist."}</p></div></div></section>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="inline-flex border border-gray-300 bg-[#FFFCFB]">{(["industrial", "retail"] as Sector[]).map((item) => <button key={item} onClick={() => { setSector(item); setDraft(null); }} className={`h-10 px-5 text-sm font-semibold capitalize ${sector === item ? "bg-[#003366] text-white border-b-2 border-[#C9AB4C]" : "text-gray-500 hover:text-[#003366]"}`}>{item}</button>)}</div><div className="flex gap-2"><button onClick={() => setBulkOpen(!bulkOpen)} className="h-10 px-4 bg-[#FFFCFB] border border-gray-300 text-[#003366] text-sm font-semibold hover:border-[#C9AB4C]">Bulk import</button><button onClick={() => setDraft(emptyDraft(sector))} className="h-10 px-4 bg-[#003366] text-white text-sm font-semibold flex items-center gap-2 hover:bg-[#00264d]"><Plus size={16}/> Add article</button></div></div>
    {bulkOpen && <section className="bg-[#FFFCFB] border border-[#C9AB4C] p-5 shadow-sm"><div className="flex justify-between gap-3 mb-3"><div><h2 className="font-serif italic text-xl text-[#003366]">Bulk import archive</h2><p className="text-xs text-gray-500 mt-1">Paste a JSON array. Existing date-and-company records will be skipped.</p></div><button onClick={() => setBulkOpen(false)} className="text-gray-400 hover:text-gray-700"><X size={18}/></button></div><textarea value={bulkText} onChange={(e) => setBulkText(e.target.value)} placeholder='[{"sector":"industrial","date":"2026-09-10","company":"...","event":"...","implications":"...","source":"..."}]' className="w-full min-h-48 border border-gray-300 p-3 font-mono text-xs leading-5 text-[#1b1d1e]" aria-label="Bulk import JSON"/><div className="mt-4 flex justify-end"><button disabled={saving || !bulkText.trim()} onClick={importBulk} className="h-10 px-4 bg-[#003366] text-white text-sm font-semibold flex items-center gap-2 disabled:opacity-60"><Save size={15}/>{saving ? "Importing…" : "Import records"}</button></div></section>}
    {draft && <section className="bg-[#FFFCFB] border border-[#C9AB4C] p-5 shadow-sm"><div className="flex justify-between gap-3 mb-4"><h2 className="font-serif italic text-xl text-[#003366]">New {sector} article</h2><button onClick={() => setDraft(null)} className="text-gray-400 hover:text-gray-700"><X size={18}/></button></div><div className="grid md:grid-cols-2 gap-4"><label className="text-xs font-bold uppercase tracking-wider text-gray-500">Date<input type="date" value={draft.date} onChange={(e) => setDraft({...draft,date:e.target.value})} className="mt-1 w-full h-10 border border-gray-300 px-3 text-sm text-[#1b1d1e]"/></label><label className="text-xs font-bold uppercase tracking-wider text-gray-500">Company / entity<input value={draft.company} onChange={(e) => setDraft({...draft,company:e.target.value})} className="mt-1 w-full h-10 border border-gray-300 px-3 text-sm text-[#1b1d1e]"/></label><label className="md:col-span-2 text-xs font-bold uppercase tracking-wider text-gray-500">Event<textarea value={draft.event} onChange={(e) => setDraft({...draft,event:e.target.value})} className="mt-1 w-full min-h-24 border border-gray-300 p-3 text-sm text-[#1b1d1e]"/></label><label className="md:col-span-2 text-xs font-bold uppercase tracking-wider text-gray-500">Implications<textarea value={draft.implications} onChange={(e) => setDraft({...draft,implications:e.target.value})} className="mt-1 w-full min-h-24 border border-gray-300 p-3 text-sm text-[#1b1d1e]"/></label><label className="md:col-span-2 text-xs font-bold uppercase tracking-wider text-gray-500">Source URL<input type="url" value={draft.source} onChange={(e) => setDraft({...draft,source:e.target.value})} placeholder="https://" className="mt-1 w-full h-10 border border-gray-300 px-3 text-sm text-[#1b1d1e]"/></label></div><div className="mt-4 flex justify-end"><button disabled={saving} onClick={save} className="h-10 px-4 bg-[#003366] text-white text-sm font-semibold flex items-center gap-2 disabled:opacity-60"><Save size={15}/>{saving ? "Saving…" : "Save to archive"}</button></div></section>}
    {error && <div className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section><div className="flex items-baseline justify-between mb-3"><h2 className="font-serif italic text-2xl text-[#003366] capitalize">{sector} archive</h2><span className="text-xs text-gray-500">{visible.length} records</span></div>{loading ? <div className="bg-[#FFFCFB] border border-gray-200 p-8 text-sm text-gray-500">Loading archive…</div> : visible.length === 0 ? <div className="bg-[#FFFCFB] border border-dashed border-gray-300 p-8 text-sm text-gray-500">No {sector} articles yet. Add the first source above.</div> : <div className="grid lg:grid-cols-2 gap-4">{visible.map((article) => <article key={article.id} className="bg-[#FFFCFB] border border-gray-200 p-5 hover:border-[#C9AB4C] transition-colors"><div className="flex justify-between gap-4"><p className="text-xs font-bold uppercase tracking-wider text-[#C9AB4C]">{article.date}</p>{isUrl(article.source) && <a href={article.source} target="_blank" rel="noreferrer" className="text-[#003366] hover:text-[#C9AB4C]" aria-label={`Open source for ${article.company}`}><ExternalLink size={16}/></a>}</div><h3 className="mt-2 text-lg font-semibold text-[#003366]">{article.company}</h3><p className="mt-3 text-sm leading-6 text-gray-700 whitespace-pre-wrap">{article.event}</p>{article.implications && <div className="mt-4 pt-3 border-t border-gray-100"><p className="text-[11px] font-bold uppercase tracking-wider text-gray-400">Implications</p><p className="mt-1 text-sm leading-6 text-gray-600 whitespace-pre-wrap">{article.implications}</p></div>}{article.source && <p className="mt-4 pt-3 border-t border-gray-100 text-xs leading-5 text-gray-500"><span className="font-bold uppercase tracking-wider text-gray-400">Source</span><br/>{article.source}</p>}</article>)}</div>}</section>
  </div>;
}
