import { DemandRecord } from "@/types/demands";

export const DEMANDS_CLICKUP_LIST_ID = "901420989525";

export function formatDemandClickUpTitle(demand: DemandRecord, index?: number, total?: number): string {
  const min = Number(demand.minSqm).toLocaleString();
  const max = Number(demand.maxSqm).toLocaleString();
  const sqmRange = demand.minSqm === demand.maxSqm ? `${max} sqm` : `${min}-${max} sqm`;
  const siteIndex = total && total > 1 && index !== undefined ? ` [Site ${index + 1}/${total}]` : '';

  return `[${demand.type}] ${demand.client} — ${sqmRange} | ${demand.city}, ${demand.location} (${demand.assoc})${siteIndex}`;
}

export function formatDemandClickUpDescription(demand: DemandRecord): string {
  const min = Number(demand.minSqm).toLocaleString();
  const max = Number(demand.maxSqm).toLocaleString();
  const sqmRange = demand.minSqm === demand.maxSqm ? `${max} sqm` : `${min} – ${max} sqm`;

  return `## Corporate Tenant Demand Brief

| Parameter | Specification |
|:---|:---|
| **Client / Brand** | ${demand.client} |
| **Industry / Concept** | ${demand.industry} |
| **Asset Classification** | ${demand.type === 'INDL' ? 'Industrial / Logistics (INDL)' : demand.type === 'CL' ? 'Commercial Lease (CL)' : 'Commercial Space (CS)'} |
| **Area Requirement** | ${sqmRange} |
| **Target Region (G.LOC)** | ${demand.gloc} |
| **Target City** | ${demand.city} |
| **Specific Corridor / Location** | ${demand.location} |
| **Priority Level** | ${demand.priority.toUpperCase()} |
| **Mandate Purpose** | ${demand.purpose || 'Expansion'} |
| **Timeline / Target Opening** | ${demand.timeline || 'Immediate'} |
| **Associate in Charge** | ${demand.assoc} |
| **Lead Source** | ${demand.source || 'Existing Network'} |
| **Intake Date** | ${demand.date} |

### Technical Specifications & Operational Notes
${demand.remarks || 'Standard commercial terms and tenant specifications apply.'}

---
*Generated by Prime Philippines CRE Demands Intelligence Engine for ClickUp List 901420989525*`;
}

export async function pushDemandToClickUp(
  demand: DemandRecord,
  token?: string,
  index?: number,
  total?: number
): Promise<{ success: boolean; id?: string; url?: string; error?: string }> {
  const clickUpToken = token || process.env.CLICKUP_API_TOKEN || process.env.CLICKUP_ACCESS_TOKEN;
  if (!clickUpToken) {
    return {
      success: false,
      error: "ClickUp token is not configured in environment or settings"
    };
  }

  const title = formatDemandClickUpTitle(demand, index, total);
  const markdownDesc = formatDemandClickUpDescription(demand);

  // Map priority: ClickUp 1: Urgent, 2: High, 3: Normal, 4: Low
  let priorityVal = 3;
  if (demand.priority === 'Priority') priorityVal = 1;
  else if (demand.priority === 'Low' || demand.priority === 'Shelved') priorityVal = 4;

  try {
    const res = await fetch(`https://api.clickup.com/api/v2/list/${DEMANDS_CLICKUP_LIST_ID}/task`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': clickUpToken
      },
      body: JSON.stringify({
        name: title,
        markdown_description: markdownDesc,
        priority: priorityVal,
        tags: [demand.type.toLowerCase(), demand.gloc.toLowerCase(), demand.industry.toLowerCase().replace(/[^a-z0-9]/g, '-')]
      })
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      return {
        success: false,
        error: errData.err || errData.message || `ClickUp API error ${res.status}`
      };
    }

    const data = await res.json();
    return {
      success: true,
      id: data.id,
      url: data.url
    };
  } catch (err: any) {
    return {
      success: false,
      error: err?.message || 'Network error syncing with ClickUp'
    };
  }
}
