"use client";

import { FormEvent, useState } from "react";
import { Bug, Send } from "lucide-react";
import { readJsonResponse } from "@/lib/forms/clientResponse";

export default function ITBugErrorReportForm({ listId, user }: { listId: string; user?: { name?: string; email?: string } | null }) {
  const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; setSaving(true); setNotice(""); try { const payload = new FormData(formElement); payload.append("listId", listId); payload.append("requestorName", user?.name || ""); const response = await fetch("/api/forms/it-bug-error-report", { method: "POST", body: payload }); const data = await readJsonResponse<{ error?: string; taskUrl?: string; taskId?: string; formRequestId?: string }>(response); if (!response.ok) throw new Error(data.error || "Unable to submit bug report."); setNotice(`Submitted to ClickUp: ${data.taskUrl || data.taskId}`); window.dispatchEvent(new CustomEvent("echo-form-submitted", { detail: data })); formElement.reset(); } catch (error: any) { setNotice(error.message || "Unable to submit bug report."); } finally { setSaving(false); } };
  return <form id="it-bug-error-report-form" onSubmit={submit} className="max-w-[850px] mx-auto border border-slate-300 bg-[#FFFCFB] shadow-sm p-7 text-[#172033]"><div className="flex items-start justify-between border-b-2 border-[#003366] pb-3 mb-5"><div className="flex gap-3"><Bug className="text-[#C9AB4C] shrink-0" size={25} /><div><h2 className="text-xl font-bold text-[#003366]">Bug/Error Report</h2><p className="text-xs text-slate-500 mt-1">Report software bugs, errors, or unexpected behavior for IT investigation.</p></div></div><span className="text-[10px] font-bold uppercase tracking-widest text-[#C9AB4C]">IT Department</span></div><label className="block text-xs font-bold">Issue name *<input required name="issueName" placeholder='e.g. “Login page not loading”' className="mt-1 w-full border border-slate-300 px-3 py-2 font-normal" /></label><label className="block text-xs font-bold mt-3">Issue description *<textarea required name="issueDescription" rows={5} placeholder="Describe what happened, steps to reproduce, and any error message." className="mt-1 w-full border border-slate-300 px-3 py-2 font-normal resize-none" /></label><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><label className="text-xs font-bold">Email *<input required readOnly name="email" value={user?.email || ""} className="mt-1 w-full border border-slate-300 bg-[#FFFCFB] px-3 py-2 font-normal" /></label><label className="text-xs font-bold">Department *<input required name="department" defaultValue="IT" className="mt-1 w-full border border-slate-300 px-3 py-2 font-normal" /></label></div><label className="block text-xs font-bold mt-3">Attachments<span className="block text-[10px] font-normal text-slate-400 mb-1">Attach screenshots, screen recordings, or error logs.</span><input name="attachments" type="file" multiple className="w-full border border-dashed border-slate-300 px-3 py-2 text-xs font-normal" /></label>{notice && <div className="mt-3 border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-900">{notice}</div>}<button disabled={saving} className="hidden" type="submit"><Send size={15} />{saving ? "Submitting…" : "Submit Bug Report"}</button></form>;
}
